services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "1024:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - lemp-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        - CONTAINER_NAME=wp
    image: wordpress
    container_name: wp
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - lemp-network
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_HOST=db
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: db
    restart: unless-stopped
    volumes:
      - mariadb:${DB_DIR}
    networks:
      - lemp-network
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - DB_DIR=${DB_DIR}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  wordpress:
    driver_opts:
      type: none
      device: ${HOME}/data/html
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

networks:
  lemp-network:
    driver: bridge
