services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - web:/var/www/
    networks:
      - lemp-network
    environment:
      - DOMAIN=${DOMAIN}

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wp
    restart: unless-stopped
    volumes:
      - web:/var/www/
    networks:
      - lemp-network
    environment:
      - WP_DB_NAME=${DB_NAME}
      - WP_DB_USER=${DB_USER}
      - WP_DB_HOST=${DB_HOST}
      - WP_CREDENTIALS_FILE=/run/secrets/wp_credentials
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DOMAIN=${DOMAIN}
    secrets:
      - db_password
      - wp_credentials

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: db
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mariadb/
    networks:
      - lemp-network
    expose:
      - 3306
    environment:
      - DB_DIR=/var/lib/mariadb/
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

volumes:
  web:
    driver_opts:
      type: none
      device: ${HOME}/data/www
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

networks:
  lemp-network:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  wp_credentials:
    file: ../secrets/wp_credentials.json
