FROM alpine:3.20


RUN apk add --no-cache \
    php83 \
    php82-fpm \
    # wget 

    # RUN wget https://wordpress.org/latest.tar.gz &&\
    #     mkdir -p /var/www/html/ &&\
    #     tar -xf latest.tar.gz && \
    #     mv wordpress/* /var/www/html/ && \
    #     rm -rf latest.tar.gz wordpress

    # CMD ["/usr/sbin/php-fpm84", "-F"]
